# Generated by Django 4.2 on 2026-03-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=100, verbose_name='资产编号')),
                ('asset_name', models.CharField(max_length=200, verbose_name='资产名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='位置')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='机房')),
                ('rack', models.CharField(blank=True, max_length=100, verbose_name='机柜')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='位置')),
                ('status', models.CharField(choices=[('ACTIVE', '活跃'), ('INACTIVE', '停用'), ('MAINTENANCE', '维护中'), ('DECOMMISSIONED', '已退役')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('importance_level', models.CharField(choices=[('LOW', '低'), ('MEDIUM', '中'), ('HIGH', '高'), ('CRITICAL', '关键')], default='MEDIUM', max_length=20, verbose_name='重要等级')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('warranty_end', models.DateField(blank=True, null=True, verbose_name='保修到期')),
                ('decommission_date', models.DateField(blank=True, null=True, verbose_name='退役日期')),
                ('owner', models.CharField(blank=True, max_length=100, verbose_name='负责人')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('vendor', models.CharField(blank=True, max_length=100, verbose_name='供应商')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产管理',
                'db_table': 'assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_value', models.TextField(blank=True, verbose_name='字符串值')),
                ('number_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='数字值')),
                ('boolean_value', models.BooleanField(blank=True, null=True, verbose_name='布尔值')),
                ('date_value', models.DateField(blank=True, null=True, verbose_name='日期值')),
                ('datetime_value', models.DateTimeField(blank=True, null=True, verbose_name='日期时间值')),
                ('json_value', models.JSONField(blank=True, null=True, verbose_name='JSON值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产数据',
                'verbose_name_plural': '资产数据管理',
                'db_table': 'asset_data',
            },
        ),
        migrations.CreateModel(
            name='AssetField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_code', models.CharField(max_length=50, verbose_name='字段代码')),
                ('field_name', models.CharField(max_length=100, verbose_name='字段名称')),
                ('field_type', models.CharField(choices=[('string', '字符串'), ('number', '数字'), ('boolean', '布尔值'), ('date', '日期'), ('datetime', '日期时间'), ('select', '下拉选择'), ('textarea', '文本域'), ('password', '密码')], max_length=20, verbose_name='字段类型')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('is_unique', models.BooleanField(default=False, verbose_name='是否唯一')),
                ('is_searchable', models.BooleanField(default=True, verbose_name='是否可搜索')),
                ('is_filterable', models.BooleanField(default=True, verbose_name='是否可过滤')),
                ('field_label', models.CharField(max_length=100, verbose_name='显示标签')),
                ('placeholder', models.CharField(blank=True, max_length=200, verbose_name='占位符')),
                ('help_text', models.TextField(blank=True, verbose_name='帮助文本')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('validation_rules', models.JSONField(blank=True, default=dict, verbose_name='验证规则')),
                ('default_value', models.TextField(blank=True, verbose_name='默认值')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='选项列表')),
            ],
            options={
                'verbose_name': '资产字段',
                'verbose_name_plural': '资产字段管理',
                'db_table': 'asset_fields',
                'ordering': ['sort_order', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=50, verbose_name='类型代码')),
                ('type_name', models.CharField(max_length=100, verbose_name='类型名称')),
                ('plugin_id', models.CharField(blank=True, max_length=100, verbose_name='插件ID')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='颜色')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_system', models.BooleanField(default=False, verbose_name='是否系统类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产类型',
                'verbose_name_plural': '资产类型管理',
                'db_table': 'asset_types',
                'ordering': ['sort_order', 'type_name'],
            },
        ),
    ]
