# Generated by Django 4.2 on 2026-03-28 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_types', to='customers.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='assettype',
            name='parent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.assettype', verbose_name='父类型'),
        ),
        migrations.AddField(
            model_name='assetfield',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='assets.assettype', verbose_name='资产类型'),
        ),
        migrations.AddField(
            model_name='assetdata',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='assets.asset', verbose_name='资产'),
        ),
        migrations.AddField(
            model_name='assetdata',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='assets.assetfield', verbose_name='字段'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assettype', verbose_name='资产类型'),
        ),
    ]
