# Generated by Django 4.2 on 2026-03-28 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='asset',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='customers.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_assets', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AlterUniqueTogether(
            name='assettype',
            unique_together={('customer', 'type_code')},
        ),
        migrations.AlterUniqueTogether(
            name='assetfield',
            unique_together={('asset_type', 'field_code')},
        ),
        migrations.AddIndex(
            model_name='assetdata',
            index=models.Index(fields=['asset'], name='asset_data_asset_i_11afb4_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdata',
            index=models.Index(fields=['field'], name='asset_data_field_i_e89921_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetdata',
            unique_together={('asset', 'field')},
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_code'], name='assets_asset_c_4e968f_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_status_326766_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type'], name='assets_asset_t_57ae73_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['customer', 'status'], name='assets_custome_cdfca9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('customer', 'asset_code')},
        ),
    ]
