# Generated by Django 4.2 on 2026-03-28 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_check_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后检查时间'),
        ),
        migrations.AddField(
            model_name='asset',
            name='online',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否在线'),
        ),
        migrations.CreateModel(
            name='AssetStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', '活跃'), ('INACTIVE', '停用'), ('MAINTENANCE', '维护中'), ('DECOMMISSIONED', '已退役')], max_length=20, verbose_name='状态')),
                ('changed_by', models.CharField(default='SYSTEM', max_length=100, verbose_name='变更人')),
                ('change_reason', models.TextField(blank=True, verbose_name='变更原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='assets.asset', verbose_name='资产')),
            ],
            options={
                'verbose_name': '资产状态历史',
                'verbose_name_plural': '资产状态历史',
                'db_table': 'asset_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assetstatushistory',
            index=models.Index(fields=['asset', 'created_at'], name='asset_statu_asset_i_07441f_idx'),
        ),
    ]
