# Generated by Django 4.2 on 2026-03-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_add_online_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '活跃'), ('INACTIVE', '停用'), ('ONLINE', '在线'), ('OFFLINE', '离线'), ('MAINTENANCE', '维护中'), ('DECOMMISSIONED', '已退役')], default='ACTIVE', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='assetstatushistory',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '活跃'), ('INACTIVE', '停用'), ('ONLINE', '在线'), ('OFFLINE', '离线'), ('MAINTENANCE', '维护中'), ('DECOMMISSIONED', '已退役')], max_length=20, verbose_name='状态'),
        ),
    ]
