# Generated by Django 4.2 on 2026-04-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0005_alter_asset_status_alter_assetstatushistory_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="database",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="数据库名"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="db_type",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="数据库类型"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="password",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="密码"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="port",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="端口"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="protocol",
            field=models.CharField(
                blank=True,
                choices=[
                    ("snmp", "SNMP"),
                    ("ssh", "SSH"),
                    ("ping", "Ping"),
                    ("mysql", "MySQL"),
                    ("mssql", "MSSQL"),
                    ("oracle", "Oracle"),
                    ("postgresql", "PostgreSQL"),
                    ("port", "端口检测"),
                ],
                default="",
                max_length=20,
                verbose_name="采集协议",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="username",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="用户名"
            ),
        ),
    ]
