# Generated by Django 4.2 on 2026-04-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="键"),
                ),
                ("value", models.TextField(blank=True, default="", verbose_name="值")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "基本设置"),
                            ("push", "推送设置"),
                            ("notification", "通知设置"),
                            ("security", "安全设置"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="分类",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=200, verbose_name="显示名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "field_type",
                    models.CharField(
                        default="string",
                        help_text="string/boolean/json/password/select",
                        max_length=20,
                        verbose_name="字段类型",
                    ),
                ),
                (
                    "options",
                    models.JSONField(blank=True, default=list, verbose_name="选项列表"),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="如密码、Token等，前端展示时脱敏",
                        verbose_name="敏感信息",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "updated_by",
                    models.CharField(blank=True, max_length=100, verbose_name="更新人"),
                ),
            ],
            options={
                "verbose_name": "系统设置",
                "verbose_name_plural": "系统设置",
                "db_table": "system_settings",
                "ordering": ["category", "key"],
            },
        ),
    ]
