# Generated by Django 4.2 on 2026-03-30 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0005_alter_asset_status_alter_assetstatushistory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='工单标题')),
                ('resume', models.CharField(blank=True, max_length=500, null=True, verbose_name='摘要')),
                ('contact_name', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('order_type', models.IntegerField(blank=True, choices=[(1, '技术'), (2, '销售'), (3, '其他')], null=True, verbose_name='工单类型')),
                ('priority', models.IntegerField(choices=[(0, '普通'), (1, '紧急'), (2, '重要')], default=0, verbose_name='优先级')),
                ('status', models.IntegerField(choices=[(0, '新建'), (1, '处理中'), (2, '搁置'), (3, '已完成')], default=0, verbose_name='状态')),
                ('occdate', models.DateTimeField(blank=True, null=True, verbose_name='发生时间')),
                ('cttime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.TextField(blank=True, verbose_name='详细描述')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='assets.asset', verbose_name='关联资产')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='customers.customer', verbose_name='客户')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_orders', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单管理',
                'db_table': 'work_orders',
                'ordering': ['-cttime'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '新建'), (1, '处理中'), (2, '搁置'), (3, '已完成')], default=0, verbose_name='状态')),
                ('step_type', models.CharField(default='followup', max_length=50, verbose_name='步骤类型')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='步骤标题')),
                ('description', models.TextField(blank=True, verbose_name='处理描述')),
                ('attachment', models.CharField(blank=True, max_length=500, verbose_name='附件路径')),
                ('flow_time', models.DateTimeField(blank=True, null=True, verbose_name='跟进时间')),
                ('cttime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_steps', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workorder.workorder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '工单步骤',
                'verbose_name_plural': '工单步骤管理',
                'db_table': 'work_order_steps',
                'ordering': ['-cttime'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('cttime', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workorder.workorder', verbose_name='工单')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
            ],
            options={
                'verbose_name': '工单评论',
                'verbose_name_plural': '工单评论管理',
                'db_table': 'work_order_comments',
                'ordering': ['-cttime'],
            },
        ),
    ]
