# Generated by Django 4.2 on 2026-04-08 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inspection", "0008_add_inspection_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdhocTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                ("task_type", models.CharField(max_length=50, verbose_name="任务类型")),
                ("task_config", models.JSONField(default=dict, verbose_name="任务配置")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(blank=True, max_length=100, verbose_name="触发者"),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "duration_ms",
                    models.IntegerField(blank=True, null=True, verbose_name="持续时间(ms)"),
                ),
                ("result_data", models.JSONField(default=dict, verbose_name="结果数据")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "临时任务",
                "db_table": "scheduler_v2_adhoc_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="计划名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("inspection", "巡检计划"),
                            ("push", "推送计划"),
                            ("monitoring", "监控计划"),
                            ("discovery", "发现计划"),
                            ("mixed", "综合计划"),
                        ],
                        default="mixed",
                        max_length=50,
                        verbose_name="计划类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "启用"),
                            ("paused", "暂停"),
                            ("archived", "归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "inspection_plan_name",
                    models.CharField(blank=True, max_length=200, verbose_name="关联巡检名称"),
                ),
                (
                    "trigger_mode",
                    models.CharField(
                        choices=[
                            ("schedule", "定时调度"),
                            ("adhoc", "临时执行"),
                            ("manual", "手动触发"),
                        ],
                        default="schedule",
                        max_length=20,
                        verbose_name="触发模式",
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Cron表达式"
                    ),
                ),
                (
                    "interval_seconds",
                    models.IntegerField(blank=True, null=True, verbose_name="间隔秒数"),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("max_concurrent", models.IntegerField(default=1, verbose_name="最大并发")),
                (
                    "timeout_seconds",
                    models.IntegerField(default=3600, verbose_name="超时秒数"),
                ),
                (
                    "next_run_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="下次运行时间"),
                ),
                (
                    "last_run_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="上次运行时间"),
                ),
                (
                    "total_executions",
                    models.IntegerField(default=0, verbose_name="总执行次数"),
                ),
                ("success_count", models.IntegerField(default=0, verbose_name="成功次数")),
                ("failure_count", models.IntegerField(default=0, verbose_name="失败次数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "inspection_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduler_plans",
                        to="inspection.inspectionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务计划",
                "db_table": "scheduler_v2_plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                            ("timeout", "超时"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("schedule", "定时调度"),
                            ("adhoc", "临时执行"),
                            ("manual", "手动触发"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="触发方式",
                    ),
                ),
                ("total_tasks", models.IntegerField(default=0, verbose_name="总任务数")),
                (
                    "completed_tasks",
                    models.IntegerField(default=0, verbose_name="完成任务数"),
                ),
                ("success_tasks", models.IntegerField(default=0, verbose_name="成功任务数")),
                ("failed_tasks", models.IntegerField(default=0, verbose_name="失败任务数")),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "duration_ms",
                    models.IntegerField(blank=True, null=True, verbose_name="持续时间(ms)"),
                ),
                ("result_data", models.JSONField(default=dict, verbose_name="结果数据")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="scheduler_v2.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "计划执行记录",
                "db_table": "scheduler_v2_plan_executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("inspection", "巡检任务"),
                            ("push_alert", "告警推送"),
                            ("push_inspection", "巡检结果推送"),
                            ("push_status", "状态推送"),
                            ("status_refresh", "状态刷新"),
                            ("discovery_scan", "发现扫描"),
                            ("cleanup", "数据清理"),
                            ("report", "生成报表"),
                            ("dashboard_refresh", "仪表盘刷新"),
                        ],
                        max_length=50,
                        verbose_name="任务类型",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("task_config", models.JSONField(default=dict, verbose_name="任务配置")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "execution_order",
                    models.IntegerField(default=0, verbose_name="执行顺序"),
                ),
                (
                    "timeout_seconds",
                    models.IntegerField(default=300, verbose_name="超时秒数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="scheduler_v2.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "计划任务",
                "db_table": "scheduler_v2_plan_tasks",
                "ordering": ["execution_order"],
            },
        ),
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="模板名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("inspection", "巡检"),
                            ("push", "推送"),
                            ("monitoring", "监控"),
                            ("discovery", "发现"),
                            ("maintenance", "维护"),
                        ],
                        max_length=50,
                        verbose_name="类别",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="Setting", max_length=50, verbose_name="图标"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#409EFF", max_length=20, verbose_name="颜色"
                    ),
                ),
                ("task_type", models.CharField(max_length=50, verbose_name="任务类型")),
                ("default_config", models.JSONField(default=dict, verbose_name="默认配置")),
                ("usage_count", models.IntegerField(default=0, verbose_name="使用次数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "任务模板",
                "db_table": "scheduler_v2_task_templates",
            },
        ),
        migrations.CreateModel(
            name="TaskInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                            ("timeout", "超时"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "duration_ms",
                    models.IntegerField(blank=True, null=True, verbose_name="持续时间(ms)"),
                ),
                ("result_data", models.JSONField(default=dict, verbose_name="结果数据")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "plan_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_instances",
                        to="scheduler_v2.planexecution",
                    ),
                ),
                (
                    "plan_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="scheduler_v2.plantask",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务实例",
                "db_table": "scheduler_v2_task_instances",
                "ordering": ["id"],
            },
        ),
    ]
