[global]
    tds version = 7.4
    client charset = UTF-8
    timeout = 10
    connect timeout = 10
    encryption = off
    try server login = yes
    # 禁用证书验证（自签名证书场景）
    tls check certificate = no

[mssql]
    host = 192.168.1.11
    port = 1433
    tds version = 7.4
    encryption = off
