# Generated by Django 4.2 on 2026-03-30 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_api_key_customer_api_secret_and_more'),
        ('assets', '0005_alter_asset_status_alter_assetstatushistory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='订阅名称')),
                ('channel', models.CharField(choices=[('EMAIL', '邮件'), ('SMS', '短信'), ('WECHAT', '企业微信'), ('DINGTALK', '钉钉'), ('WEBHOOK', 'Webhook')], max_length=20, verbose_name='通知渠道')),
                ('config', models.JSONField(default=dict, verbose_name='渠道配置')),
                ('severity_filter', models.JSONField(blank=True, default=list, verbose_name='严重程度过滤')),
                ('alert_type_filter', models.JSONField(blank=True, default=list, verbose_name='告警类型过滤')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to='customers.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '告警订阅',
                'verbose_name_plural': '告警订阅管理',
                'db_table': 'alert_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, verbose_name='规则描述')),
                ('status', models.CharField(choices=[('ACTIVE', '启用'), ('INACTIVE', '停用')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('severity', models.IntegerField(choices=[(1, '信息'), (2, '警告'), (3, '错误'), (4, '严重')], default=2, verbose_name='告警严重程度')),
                ('conditions', models.JSONField(default=list, verbose_name='触发条件')),
                ('auto_create_workorder', models.BooleanField(default=True, verbose_name='自动创建工单')),
                ('workorder_template', models.JSONField(blank=True, default=dict, verbose_name='工单模板')),
                ('notify_enabled', models.BooleanField(default=False, verbose_name='启用通知')),
                ('notify_channels', models.JSONField(default=list, verbose_name='通知渠道')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='customers.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '告警规则',
                'verbose_name_plural': '告警规则管理',
                'db_table': 'alerts_alert_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='告警标题')),
                ('description', models.TextField(blank=True, verbose_name='告警描述')),
                ('severity', models.IntegerField(choices=[(1, '信息'), (2, '警告'), (3, '错误'), (4, '严重')], default=2, verbose_name='严重程度')),
                ('alert_type', models.CharField(blank=True, max_length=50, verbose_name='告警类型')),
                ('source', models.CharField(choices=[('LOCAL', '本地监控'), ('MANUAL', '手动'), ('SCHEDULED', '定时任务')], default='LOCAL', max_length=20, verbose_name='告警来源')),
                ('status', models.CharField(choices=[('NEW', '新告警'), ('ACKNOWLEDGED', '已确认'), ('IN_PROGRESS', '处理中'), ('RESOLVED', '已解决'), ('CLOSED', '已关闭')], default='NEW', max_length=20, verbose_name='状态')),
                ('alert_data', models.JSONField(blank=True, default=dict, verbose_name='告警详情')),
                ('metric_name', models.CharField(blank=True, max_length=100, verbose_name='指标名称')),
                ('metric_value', models.CharField(blank=True, max_length=100, verbose_name='指标值')),
                ('threshold', models.CharField(blank=True, max_length=100, verbose_name='阈值')),
                ('occurred_at', models.DateTimeField(blank=True, null=True, verbose_name='发生时间')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_alerts', to='assets.asset', verbose_name='资产')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_alerts', to='customers.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '告警',
                'verbose_name_plural': '告警管理',
                'db_table': 'alerts_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['customer', 'status'], name='alerts_aler_custome_41279c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['created_at'], name='alerts_aler_created_8af5ce_idx'),
        ),
    ]
