# Generated by Django 4.2 on 2026-04-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="source",
            field=models.CharField(
                choices=[
                    ("PING", "连通性检测"),
                    ("INSPECTION", "巡检结果"),
                    ("LOCAL", "本地监控"),
                    ("MANUAL", "手动"),
                    ("SCHEDULED", "定时任务"),
                ],
                default="LOCAL",
                max_length=20,
                verbose_name="告警来源",
            ),
        ),
    ]
