# Generated by Django 4.2 on 2026-03-28 05:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('task_type', models.CharField(choices=[('ping', 'Ping检测'), ('port', '端口检测'), ('snmp', 'SNMP检测'), ('http', 'HTTP检测'), ('ssl', 'SSL证书检测'), ('performance', '性能采集')], max_length=20, verbose_name='任务类型')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='任务配置')),
                ('interval', models.IntegerField(choices=[(60, '1分钟'), (300, '5分钟'), (600, '10分钟'), (1800, '30分钟'), (3600, '1小时'), (86400, '每天')], default=300, validators=[django.core.validators.MinValueValidator(60)], verbose_name='执行间隔(秒)')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_critical', models.BooleanField(default=False, verbose_name='是否关键任务')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '执行失败')], default='pending', max_length=20, verbose_name='状态')),
                ('last_run_time', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('next_run_time', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功次数')),
                ('failure_count', models.IntegerField(default=0, verbose_name='失败次数')),
                ('last_success_time', models.DateTimeField(blank=True, null=True, verbose_name='上次成功时间')),
                ('last_failure_time', models.DateTimeField(blank=True, null=True, verbose_name='上次失败时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_tasks', to='assets.asset', verbose_name='监控资产')),
            ],
            options={
                'verbose_name': '监控任务',
                'verbose_name_plural': '监控任务管理',
                'db_table': 'monitoring_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '成功'), ('warning', '警告'), ('critical', '严重'), ('timeout', '超时'), ('error', '错误'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='状态')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='响应时间(ms)')),
                ('uptime', models.FloatField(blank=True, null=True, verbose_name='可用率(%)')),
                ('cpu_usage', models.FloatField(blank=True, null=True, verbose_name='CPU使用率(%)')),
                ('memory_usage', models.FloatField(blank=True, null=True, verbose_name='内存使用率(%)')),
                ('disk_usage', models.FloatField(blank=True, null=True, verbose_name='磁盘使用率(%)')),
                ('network_in', models.FloatField(blank=True, null=True, verbose_name='入流量(Mbps)')),
                ('network_out', models.FloatField(blank=True, null=True, verbose_name='出流量(Mbps)')),
                ('port_check', models.JSONField(blank=True, default=dict, verbose_name='端口检测结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('error_details', models.JSONField(blank=True, default=dict, verbose_name='错误详情')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='持续时间(ms)')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_results', to='assets.asset', verbose_name='资产')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitoring.monitoringtask', verbose_name='监控任务')),
            ],
            options={
                'verbose_name': '监控结果',
                'verbose_name_plural': '监控结果管理',
                'db_table': 'monitoring_results',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, verbose_name='规则描述')),
                ('metric_name', models.CharField(max_length=100, verbose_name='指标名称')),
                ('condition', models.CharField(choices=[('gt', '大于'), ('lt', '小于'), ('eq', '等于'), ('ne', '不等于'), ('gte', '大于等于'), ('lte', '小于等于')], max_length=10, verbose_name='条件')),
                ('threshold', models.FloatField(verbose_name='阈值')),
                ('severity', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('critical', '严重')], default='warning', max_length=20, verbose_name='严重程度')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('check_interval', models.IntegerField(default=300, verbose_name='检查间隔(秒)')),
                ('notify_enabled', models.BooleanField(default=True, verbose_name='是否通知')),
                ('notify_channels', models.JSONField(blank=True, default=list, verbose_name='通知渠道')),
                ('notify_recipients', models.JSONField(blank=True, default=list, verbose_name='通知人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='assets.assettype', verbose_name='资产类型')),
            ],
            options={
                'verbose_name': '告警规则',
                'verbose_name_plural': '告警规则管理',
                'db_table': 'alert_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='告警标题')),
                ('message', models.TextField(verbose_name='告警信息')),
                ('severity', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('critical', '严重')], default='warning', max_length=20, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('open', '未处理'), ('acknowledged', '已确认'), ('resolved', '已解决'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='状态')),
                ('trigger_value', models.FloatField(blank=True, null=True, verbose_name='触发值')),
                ('threshold', models.FloatField(blank=True, null=True, verbose_name='阈值')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('acknowledged_by', models.CharField(blank=True, max_length=100, verbose_name='确认人')),
                ('resolved_by', models.CharField(blank=True, max_length=100, verbose_name='解决人')),
                ('resolution_note', models.TextField(blank=True, verbose_name='处理备注')),
                ('alert_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.alertrule', verbose_name='告警规则')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='assets.asset', verbose_name='资产')),
                ('monitoring_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.monitoringresult', verbose_name='监控结果')),
            ],
            options={
                'verbose_name': '告警记录',
                'verbose_name_plural': '告警记录管理',
                'db_table': 'alerts',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='monitoringresult',
            index=models.Index(fields=['asset', 'status'], name='monitoring__asset_i_e43b85_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringresult',
            index=models.Index(fields=['start_time'], name='monitoring__start_t_0fb730_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['asset', 'status'], name='alerts_asset_i_a5ee48_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'status'], name='alerts_severit_ae6d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['occurred_at'], name='alerts_occurre_73f3e4_idx'),
        ),
    ]
