# Generated by Django 4.2 on 2026-03-30 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_api_key_customer_api_secret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0005_alter_asset_status_alter_assetstatushistory_status'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('protocol', models.CharField(choices=[('ping', 'Ping'), ('port', '端口检测'), ('ssh', 'SSH'), ('snmp', 'SNMP'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mssql', 'MSSQL'), ('oracle', 'Oracle')], max_length=20, verbose_name='协议')),
                ('host', models.CharField(max_length=200, verbose_name='主机')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='端口')),
                ('config', models.JSONField(default=dict, verbose_name='协议配置')),
                ('interval', models.IntegerField(default=300, verbose_name='检测间隔')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_test_status', models.CharField(blank=True, max_length=20, verbose_name='上次状态')),
                ('last_test_time', models.DateTimeField(blank=True, null=True, verbose_name='上次测试时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_configs', to='assets.asset', verbose_name='资产')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_configs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_configs', to='customers.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '监控测试配置',
                'verbose_name_plural': '监控测试配置',
                'db_table': 'monitor_test_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitorTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('timeout', '超时'), ('error', '错误')], max_length=20, verbose_name='状态')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='响应时间(ms)')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('data', models.JSONField(default=dict, verbose_name='返回数据')),
                ('test_duration', models.FloatField(blank=True, null=True, verbose_name='测试耗时(ms)')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='来源IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='测试时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitoring.monitortestconfig', verbose_name='配置')),
            ],
            options={
                'verbose_name': '监控测试结果',
                'verbose_name_plural': '监控测试结果',
                'db_table': 'monitor_test_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='monitortestresult',
            index=models.Index(fields=['config', 'created_at'], name='monitor_tes_config__71fa0f_idx'),
        ),
    ]
