# Generated by Django 4.2 on 2026-04-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inspection", "0006_monitoring_data_point"),
        ("assets", "0006_asset_database_asset_db_type_asset_password_and_more"),
        ("customers", "0003_customer_api_key_customer_api_secret_and_more"),
        ("monitoring", "0002_monitortestconfig_monitortestresult_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoringDataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_item_code",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="检查项编码"
                    ),
                ),
                (
                    "check_item_name",
                    models.CharField(max_length=100, verbose_name="检查项名称"),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("mysql", "MySQL"),
                            ("mssql", "MSSQL"),
                            ("oracle", "Oracle"),
                            ("postgresql", "PostgreSQL"),
                            ("snmp", "SNMP"),
                            ("ssh", "SSH"),
                            ("ping", "Ping"),
                            ("port", "端口检测"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="协议类型",
                    ),
                ),
                (
                    "numeric_value",
                    models.FloatField(
                        blank=True,
                        help_text="解析后的数值，便于排序和绘图",
                        null=True,
                        verbose_name="数值",
                    ),
                ),
                (
                    "display_value",
                    models.CharField(
                        help_text='原始展示值，如 "85%"、"1523MB"',
                        max_length=200,
                        verbose_name="显示值",
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(
                        choices=[(1, "信息"), (2, "警告"), (3, "错误"), (4, "严重")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "warning_threshold",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="警告阈值"
                    ),
                ),
                (
                    "error_threshold",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="错误阈值"
                    ),
                ),
                (
                    "result_message",
                    models.TextField(blank=True, default="", verbose_name="结果消息"),
                ),
                (
                    "suggestion",
                    models.TextField(blank=True, default="", verbose_name="建议"),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(db_index=True, verbose_name="记录时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_data",
                        to="assets.asset",
                        verbose_name="资产",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_data",
                        to="customers.customer",
                        verbose_name="客户",
                    ),
                ),
                (
                    "inspection_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_points",
                        to="inspection.inspectiontask",
                        verbose_name="关联巡检任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "监控数据点",
                "verbose_name_plural": "监控数据点",
                "db_table": "monitoring_data_points",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="monitoringdatapoint",
            index=models.Index(
                fields=["asset", "check_item_code", "recorded_at"],
                name="monitoring__asset_i_9ce2e0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringdatapoint",
            index=models.Index(
                fields=["asset", "protocol", "recorded_at"],
                name="monitoring__asset_i_d3fe95_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringdatapoint",
            index=models.Index(
                fields=["customer", "recorded_at"],
                name="monitoring__custome_aca01e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringdatapoint",
            index=models.Index(
                fields=["check_item_code", "recorded_at"],
                name="monitoring__check_i_172551_idx",
            ),
        ),
    ]
