# Generated by Django 4.2 on 2026-04-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PushLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "push_type",
                    models.CharField(
                        choices=[
                            ("inspection", "巡检结果"),
                            ("alert", "告警"),
                            ("asset_status", "资产状态"),
                            ("heartbeat", "心跳检测"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="推送类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("partial", "部分成功"),
                        ],
                        default="success",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "records_count",
                    models.IntegerField(
                        default=0, help_text="本次推送的记录条数", verbose_name="推送记录数"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "endpoint",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="目标端点"
                    ),
                ),
                (
                    "request_data_size",
                    models.IntegerField(default=0, verbose_name="请求数据大小(B)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="推送时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "推送日志",
                "verbose_name_plural": "推送日志",
                "db_table": "push_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
