# Generated by Django 4.2 on 2026-04-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_push_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushlog",
            name="last_retry_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最后重试时间"),
        ),
        migrations.AddField(
            model_name="pushlog",
            name="next_retry_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="下次重试时间"),
        ),
        migrations.AddField(
            model_name="pushlog",
            name="request_payload",
            field=models.JSONField(
                blank=True, help_text="原始推送数据，支持重试", null=True, verbose_name="推送数据"
            ),
        ),
        migrations.AddField(
            model_name="pushlog",
            name="retry_count",
            field=models.IntegerField(default=0, verbose_name="重试次数"),
        ),
        migrations.AlterField(
            model_name="pushlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "成功"),
                    ("failed", "失败"),
                    ("partial", "部分成功"),
                    ("retrying", "重试中"),
                ],
                default="success",
                max_length=10,
                verbose_name="状态",
            ),
        ),
    ]
