# Generated by Django 4.2 on 2026-03-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='邮箱')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('avatar_url', models.URLField(blank=True, max_length=500, verbose_name='头像')),
                ('role', models.CharField(default='USER', max_length=50, verbose_name='角色')),
                ('permissions', models.JSONField(blank=True, default=dict, verbose_name='权限列表')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否员工')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='是否超级用户')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户管理',
                'db_table': 'users',
            },
        ),
    ]
