# Generated by Django 4.2 on 2026-04-05 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0003_customer_api_key_customer_api_secret_and_more"),
        ("assets", "0006_asset_database_asset_db_type_asset_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveredDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                (
                    "mac_address",
                    models.CharField(
                        blank=True, default="", max_length=17, verbose_name="MAC地址"
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="主机名"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("unknown", "未知"),
                            ("server", "服务器"),
                            ("router", "路由器"),
                            ("switch", "交换机"),
                            ("firewall", "防火墙"),
                            ("loadbalancer", "负载均衡器"),
                            ("storage", "存储设备"),
                            ("printer", "打印机"),
                            ("camera", "摄像头"),
                            ("access_point", "无线AP"),
                            ("workstation", "工作站"),
                            ("virtual", "虚拟机"),
                            ("cloud", "云资源"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="设备类型",
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("unknown", "未知"),
                            ("linux", "Linux"),
                            ("windows", "Windows"),
                            ("cisco_ios", "Cisco IOS"),
                            ("hp_procurve", "HP ProCurve"),
                            ("juniper_junos", "Juniper JunOS"),
                            ("fortinet", "Fortinet"),
                            ("dell_os10", "Dell OS10"),
                            ("vmware_esxi", "VMware ESXi"),
                            ("hyperv", "Hyper-V"),
                            ("aix", "AIX"),
                            ("solaris", "Solaris"),
                            ("freebsd", "FreeBSD"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="操作系统",
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="厂商"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="型号"
                    ),
                ),
                ("open_ports", models.JSONField(default=list, verbose_name="开放端口")),
                (
                    "response_time",
                    models.FloatField(blank=True, null=True, verbose_name="响应时间(ms)"),
                ),
                (
                    "snmp_sysDescr",
                    models.TextField(
                        blank=True, default="", verbose_name="SNMP sysDescr"
                    ),
                ),
                (
                    "snmp_sysName",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="SNMP sysName",
                    ),
                ),
                (
                    "snmp_sysLocation",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="SNMP sysLocation",
                    ),
                ),
                (
                    "ssh_banner",
                    models.TextField(blank=True, default="", verbose_name="SSH Banner"),
                ),
                (
                    "http_title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="HTTP Title",
                    ),
                ),
                ("is_online", models.BooleanField(default=True, verbose_name="是否在线")),
                ("raw_data", models.JSONField(default=dict, verbose_name="原始数据")),
                (
                    "is_imported",
                    models.BooleanField(default=False, verbose_name="是否已导入"),
                ),
                (
                    "discovered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发现时间"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discovered_devices",
                        to="customers.customer",
                        verbose_name="客户",
                    ),
                ),
                (
                    "imported_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovery_records",
                        to="assets.asset",
                        verbose_name="导入的资产",
                    ),
                ),
            ],
            options={
                "verbose_name": "发现的设备",
                "verbose_name_plural": "发现的设备",
                "db_table": "discovered_devices",
                "ordering": ["ip_address"],
            },
        ),
        migrations.CreateModel(
            name="TopologyNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="节点名称")),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("asset", "资产"),
                            ("subnet", "子网"),
                            ("internet", "互联网"),
                            ("cloud", "云"),
                        ],
                        default="asset",
                        max_length=20,
                        verbose_name="节点类型",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True, default="", max_length=17, verbose_name="MAC地址"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="位置"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        default="unknown", max_length=20, verbose_name="设备类型"
                    ),
                ),
                ("is_online", models.BooleanField(default=True, verbose_name="是否在线")),
                (
                    "x_position",
                    models.FloatField(blank=True, null=True, verbose_name="X坐标"),
                ),
                (
                    "y_position",
                    models.FloatField(blank=True, null=True, verbose_name="Y坐标"),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="元数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="topology_nodes",
                        to="assets.asset",
                        verbose_name="关联资产",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topology_nodes",
                        to="customers.customer",
                        verbose_name="客户",
                    ),
                ),
                (
                    "discovered_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="topology_nodes",
                        to="discovery.discovereddevice",
                        verbose_name="关联发现设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "拓扑节点",
                "verbose_name_plural": "拓扑节点",
                "db_table": "topology_nodes",
                "ordering": ["node_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="TopologyEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edge_type",
                    models.CharField(
                        choices=[
                            ("wired", "有线"),
                            ("wireless", "无线"),
                            ("logical", "逻辑"),
                            ("vlan", "VLAN"),
                        ],
                        default="wired",
                        max_length=20,
                        verbose_name="连线类型",
                    ),
                ),
                (
                    "bandwidth",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="带宽"
                    ),
                ),
                (
                    "latency",
                    models.IntegerField(blank=True, null=True, verbose_name="延迟(ms)"),
                ),
                (
                    "source_port",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="源端口"
                    ),
                ),
                (
                    "target_port",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="目标端口"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="描述"
                    ),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="元数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topology_edges",
                        to="customers.customer",
                        verbose_name="客户",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="discovery.topologynode",
                        verbose_name="源节点",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="discovery.topologynode",
                        verbose_name="目标节点",
                    ),
                ),
            ],
            options={
                "verbose_name": "拓扑连线",
                "verbose_name_plural": "拓扑连线",
                "db_table": "topology_edges",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscoveryTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                ("description", models.TextField(blank=True, verbose_name="任务描述")),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("ping", "Ping扫描"),
                            ("tcp", "TCP端口扫描"),
                            ("snmp", "SNMP扫描"),
                            ("full", "完整扫描"),
                            ("arp", "ARP扫描"),
                        ],
                        default="full",
                        max_length=20,
                        verbose_name="扫描类型",
                    ),
                ),
                (
                    "target_ranges",
                    models.JSONField(
                        default=list,
                        help_text='如 ["192.168.1.1-254", "10.0.0.1-254"]',
                        verbose_name="目标网段",
                    ),
                ),
                (
                    "ports",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="如 [22, 23, 80, 443, 161, 3306, 5432]",
                        verbose_name="扫描端口",
                    ),
                ),
                ("timeout", models.IntegerField(default=5, verbose_name="超时时间(秒)")),
                (
                    "snmp_community",
                    models.CharField(
                        blank=True,
                        default="public",
                        max_length=100,
                        verbose_name="SNMP Community",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "执行失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("total_ips", models.IntegerField(default=0, verbose_name="总IP数")),
                ("scanned_ips", models.IntegerField(default=0, verbose_name="已扫描IP数")),
                ("found_devices", models.IntegerField(default=0, verbose_name="发现设备数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "created_by",
                    models.CharField(
                        default="SYSTEM", max_length=100, verbose_name="创建人"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discovery_tasks",
                        to="customers.customer",
                        verbose_name="客户",
                    ),
                ),
            ],
            options={
                "verbose_name": "网络发现任务",
                "verbose_name_plural": "网络发现任务",
                "db_table": "discovery_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="discovereddevice",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="discovery.discoverytask",
                verbose_name="发现任务",
            ),
        ),
        migrations.AddIndex(
            model_name="discovereddevice",
            index=models.Index(
                fields=["ip_address"], name="discovered__ip_addr_2afbb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discovereddevice",
            index=models.Index(
                fields=["customer", "ip_address"], name="discovered__custome_ac9b42_idx"
            ),
        ),
    ]
