# Generated by Django 4.2 on 2026-04-01 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="任务名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="任务描述")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("monitoring", "监控任务"),
                            ("inspection", "巡检任务"),
                            ("backup", "备份任务"),
                            ("report", "报表任务"),
                            ("cleanup", "清理任务"),
                            ("sync", "同步任务"),
                        ],
                        max_length=50,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("asset", "资产"), ("customer", "客户"), ("all", "全部")],
                        default="all",
                        max_length=50,
                        verbose_name="目标类型",
                    ),
                ),
                (
                    "target_id",
                    models.BigIntegerField(blank=True, null=True, verbose_name="目标ID"),
                ),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, verbose_name="任务配置"),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Cron表达式"
                    ),
                ),
                (
                    "interval_seconds",
                    models.IntegerField(blank=True, null=True, verbose_name="间隔秒数"),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "is_running",
                    models.BooleanField(default=False, verbose_name="是否运行中"),
                ),
                (
                    "last_run_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="上次运行时间"),
                ),
                (
                    "next_run_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="下次运行时间"),
                ),
                (
                    "last_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("running", "运行中"),
                            ("timeout", "超时"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="上次状态",
                    ),
                ),
                ("last_result", models.TextField(blank=True, verbose_name="上次结果")),
                ("success_count", models.IntegerField(default=0, verbose_name="成功次数")),
                ("failure_count", models.IntegerField(default=0, verbose_name="失败次数")),
                ("total_runs", models.IntegerField(default=0, verbose_name="总运行次数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "计划任务",
                "verbose_name_plural": "计划任务管理",
                "db_table": "scheduled_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledTaskExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "duration_ms",
                    models.IntegerField(blank=True, null=True, verbose_name="持续时间(毫秒)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "运行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("timeout", "超时"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(blank=True, default=dict, verbose_name="结果数据"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                ("output", models.TextField(blank=True, verbose_name="输出日志")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="scheduler.scheduledtask",
                        verbose_name="任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "执行记录",
                "verbose_name_plural": "执行记录",
                "db_table": "scheduled_task_executions",
                "ordering": ["-start_time"],
            },
        ),
    ]
