# Generated by Django 4.2 on 2026-03-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=50, unique=True, verbose_name='客户编码')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户名称')),
                ('customer_type', models.CharField(blank=True, max_length=50, verbose_name='客户类型')),
                ('industry', models.CharField(blank=True, max_length=50, verbose_name='行业')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=100, verbose_name='联系邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='客户配置')),
                ('plugins', models.JSONField(blank=True, default=list, verbose_name='启用的插件')),
                ('status', models.CharField(default='ACTIVE', max_length=20, verbose_name='状态')),
                ('contract_start', models.DateField(blank=True, null=True, verbose_name='合同开始')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='合同结束')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户管理',
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
