# Generated by Django 4.2 on 2026-03-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='API Key'),
        ),
        migrations.AddField(
            model_name='customer',
            name='api_secret',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='API Secret'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_local_deployment',
            field=models.BooleanField(default=False, verbose_name='本地部署'),
        ),
        migrations.AddField(
            model_name='customer',
            name='local_endpoint',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='本地端点'),
        ),
    ]
