# Generated by Django 4.2 on 2026-03-28 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('assets', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='巡检名称')),
                ('description', models.TextField(blank=True, verbose_name='巡检描述')),
                ('inspection_type', models.CharField(choices=[('MANUAL', '手工巡检'), ('AUTO', '自动巡检'), ('SNMP', 'SNMP巡检'), ('DATABASE', '数据库巡检')], max_length=20, verbose_name='巡检类型')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='巡检配置')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('RUNNING', '执行中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='执行时长(毫秒)')),
                ('total_items', models.IntegerField(default=0, verbose_name='巡检项总数')),
                ('passed_items', models.IntegerField(default=0, verbose_name='通过项数')),
                ('warning_items', models.IntegerField(default=0, verbose_name='警告项数')),
                ('failed_items', models.IntegerField(default=0, verbose_name='失败项数')),
                ('summary', models.TextField(blank=True, verbose_name='巡检总结')),
                ('recommendations', models.TextField(blank=True, verbose_name='处理建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='assets.asset', verbose_name='资产')),
                ('asset_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='assets.assettype', verbose_name='资产类型')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspections', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='customers.customer', verbose_name='客户')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_inspections', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
            options={
                'verbose_name': '巡检记录',
                'verbose_name_plural': '巡检记录管理',
                'db_table': 'inspections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('inspection_type', models.CharField(max_length=20, verbose_name='巡检类型')),
                ('items', models.JSONField(default=list, verbose_name='巡检项配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('interval_seconds', models.IntegerField(blank=True, null=True, verbose_name='巡检间隔(秒)')),
                ('cron_expression', models.CharField(blank=True, max_length=100, verbose_name='Cron表达式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_templates', to='assets.assettype', verbose_name='资产类型')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '巡检模板',
                'verbose_name_plural': '巡检模板管理',
                'db_table': 'inspection_templates',
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100, verbose_name='巡检项代码')),
                ('item_name', models.CharField(max_length=200, verbose_name='巡检项名称')),
                ('category', models.CharField(max_length=50, verbose_name='巡检类别')),
                ('severity', models.CharField(choices=[('INFO', '信息'), ('OK', '正常'), ('WARNING', '警告'), ('CRITICAL', '严重'), ('UNKNOWN', '未知')], default='INFO', max_length=20, verbose_name='严重程度')),
                ('result', models.CharField(choices=[('PASS', '通过'), ('WARNING', '警告'), ('FAIL', '失败'), ('SKIP', '跳过'), ('ERROR', '错误')], max_length=20, verbose_name='检查结果')),
                ('threshold_config', models.JSONField(blank=True, default=dict, verbose_name='阈值配置')),
                ('actual_value', models.TextField(blank=True, verbose_name='实际值')),
                ('expected_value', models.TextField(blank=True, verbose_name='期望值')),
                ('message', models.TextField(blank=True, verbose_name='检查消息')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='详细信息')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='检查时间')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspection.inspection', verbose_name='巡检记录')),
            ],
            options={
                'verbose_name': '巡检项目',
                'verbose_name_plural': '巡检项目管理',
                'db_table': 'inspection_items',
                'ordering': ['category', 'item_code'],
            },
        ),
        migrations.AddIndex(
            model_name='inspectionitem',
            index=models.Index(fields=['inspection', 'result'], name='inspection__inspect_4c2411_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionitem',
            index=models.Index(fields=['category', 'result'], name='inspection__categor_c753be_idx'),
        ),
    ]
