# Generated by Django 4.2 on 2026-03-30 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0005_alter_asset_status_alter_assetstatushistory_status'),
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='计划编码')),
                ('description', models.TextField(blank=True, verbose_name='计划描述')),
                ('cycle', models.CharField(choices=[('daily', '每天'), ('weekly', '每周'), ('monthly', '每月'), ('quarterly', '每季度')], default='daily', max_length=20, verbose_name='执行周期')),
                ('scheduled_time', models.TimeField(verbose_name='计划执行时间')),
                ('is_auto_execute', models.BooleanField(default=False, verbose_name='是否自动执行')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('paused', '暂停'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('check_items', models.JSONField(blank=True, default=list, verbose_name='巡检项目配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '巡检计划',
                'verbose_name_plural': '巡检计划管理',
                'db_table': 'inspection_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_checks', models.IntegerField(default=0, verbose_name='总检查项')),
                ('pass_checks', models.IntegerField(default=0, verbose_name='通过项')),
                ('warning_checks', models.IntegerField(default=0, verbose_name='警告项')),
                ('fail_checks', models.IntegerField(default=0, verbose_name='不合格项')),
                ('skip_checks', models.IntegerField(default=0, verbose_name='跳过项')),
                ('status', models.CharField(choices=[('completed', '已完成'), ('partial', '部分完成'), ('failed', '失败')], max_length=20, verbose_name='巡检状态')),
                ('overall_status', models.CharField(choices=[('pass', '通过'), ('warning', '警告'), ('fail', '不合格'), ('skip', '跳过')], max_length=20, verbose_name='总体评价')),
                ('summary', models.TextField(blank=True, verbose_name='巡检总结')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='持续时间(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_records', to='assets.asset', verbose_name='资产')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_records', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
            options={
                'verbose_name': '巡检记录',
                'verbose_name_plural': '巡检记录管理',
                'db_table': 'inspection_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_item', models.CharField(max_length=100, verbose_name='检查项')),
                ('check_item_code', models.CharField(max_length=50, verbose_name='检查项编码')),
                ('status', models.CharField(choices=[('pass', '通过'), ('warning', '警告'), ('fail', '不合格'), ('skip', '跳过')], max_length=20, verbose_name='状态')),
                ('result_value', models.CharField(blank=True, max_length=500, verbose_name='检查值')),
                ('result_message', models.TextField(blank=True, verbose_name='结果说明')),
                ('expected_value', models.CharField(blank=True, max_length=200, verbose_name='期望值')),
                ('threshold_min', models.CharField(blank=True, max_length=100, verbose_name='最小阈值')),
                ('threshold_max', models.CharField(blank=True, max_length=100, verbose_name='最大阈值')),
                ('suggestion', models.TextField(blank=True, verbose_name='处理建议')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_results', to='assets.asset', verbose_name='资产')),
            ],
            options={
                'verbose_name': '巡检结果',
                'verbose_name_plural': '巡检结果管理',
                'db_table': 'inspection_results',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(verbose_name='计划巡检时间')),
                ('executed_time', models.DateTimeField(blank=True, null=True, verbose_name='实际巡检时间')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待巡检'), ('in_progress', '巡检中'), ('completed', '已完成'), ('failed', '巡检失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_tasks', to='assets.asset', verbose_name='巡检资产')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_tasks', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='inspection.inspectionplan', verbose_name='巡检计划')),
            ],
            options={
                'verbose_name': '巡检任务',
                'verbose_name_plural': '巡检任务管理',
                'db_table': 'inspection_tasks',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.RemoveField(
            model_name='inspectionitem',
            name='inspection',
        ),
        migrations.RemoveField(
            model_name='inspectiontemplate',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='inspectiontemplate',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Inspection',
        ),
        migrations.DeleteModel(
            name='InspectionItem',
        ),
        migrations.DeleteModel(
            name='InspectionTemplate',
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='inspection.inspectiontask', verbose_name='巡检任务'),
        ),
        migrations.AddField(
            model_name='inspectionrecord',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='inspection.inspectiontask', verbose_name='巡检任务'),
        ),
    ]
