# Generated by Django 4.2 on 2026-04-01 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_api_key_customer_api_secret_and_more'),
        ('inspection', '0002_inspectionplan_inspectionrecord_inspectionresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionplan',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_plans', to='customers.customer', verbose_name='所属客户'),
        ),
    ]
