# Generated by Django 4.2 on 2026-04-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspection", "0003_add_customer_to_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionplan",
            name="protocol",
            field=models.CharField(
                choices=[
                    ("mysql", "MySQL"),
                    ("mssql", "MSSQL"),
                    ("oracle", "Oracle"),
                    ("postgresql", "PostgreSQL"),
                    ("snmp", "SNMP"),
                    ("ssh", "SSH"),
                    ("ping", "Ping"),
                    ("port", "端口检测"),
                ],
                default="mysql",
                max_length=20,
                verbose_name="协议类型",
            ),
        ),
    ]
