# Generated by Django 4.2 on 2026-04-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspection", "0005_inspectionresult_severity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectionresult",
            name="severity",
            field=models.IntegerField(default=1, verbose_name="严重程度"),
        ),
    ]
