# Generated by Django 4.2 on 2026-04-05 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0006_asset_database_asset_db_type_asset_password_and_more"),
        ("customers", "0003_customer_api_key_customer_api_secret_and_more"),
        ("inspection", "0006_monitoring_data_point"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="巡检名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "inspection_type",
                    models.CharField(
                        default="SNMP", max_length=50, verbose_name="巡检类型"
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(blank=True, max_length=50, verbose_name="资产类型"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "运行中"),
                            ("COMPLETED", "已完成"),
                            ("FAILED", "失败"),
                        ],
                        default="RUNNING",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                ("total_items", models.IntegerField(default=0, verbose_name="总检查项")),
                ("passed_items", models.IntegerField(default=0, verbose_name="通过项")),
                ("warning_items", models.IntegerField(default=0, verbose_name="警告项")),
                ("failed_items", models.IntegerField(default=0, verbose_name="失败项")),
                ("duration_ms", models.IntegerField(default=0, verbose_name="耗时(ms)")),
                ("summary", models.TextField(blank=True, verbose_name="总结")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.asset",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "巡检记录",
                "db_table": "inspections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InspectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_code", models.CharField(max_length=50, verbose_name="检查项编码")),
                ("item_name", models.CharField(max_length=100, verbose_name="检查项名称")),
                ("category", models.CharField(max_length=50, verbose_name="类别")),
                (
                    "result",
                    models.CharField(
                        choices=[("PASS", "通过"), ("WARNING", "警告"), ("FAIL", "失败")],
                        default="PASS",
                        max_length=10,
                        verbose_name="结果",
                    ),
                ),
                (
                    "severity",
                    models.CharField(default="OK", max_length=20, verbose_name="严重程度"),
                ),
                (
                    "actual_value",
                    models.CharField(blank=True, max_length=500, verbose_name="实际值"),
                ),
                (
                    "expected_value",
                    models.CharField(blank=True, max_length=500, verbose_name="期望值"),
                ),
                ("message", models.TextField(blank=True, verbose_name="消息")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="详细信息"),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inspection.inspection",
                    ),
                ),
            ],
            options={
                "verbose_name": "巡检项目",
                "db_table": "inspection_items",
            },
        ),
    ]
