# Generated by Django 4.2 on 2026-04-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspection", "0007_add_inspection_and_item_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="模板名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "inspection_type",
                    models.CharField(
                        default="SNMP", max_length=50, verbose_name="巡检类型"
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(blank=True, max_length=50, verbose_name="资产类型"),
                ),
                (
                    "items",
                    models.JSONField(blank=True, default=list, verbose_name="巡检项目"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "巡检模板",
                "db_table": "inspection_templates",
            },
        ),
    ]
